src/browsered/field-validation/field-validation.test.js, src/utils/is-valid-email.test.js
Little tests for the email validator function
=> Email validator tests

package-lock.json, package.json
- Using @babel now, so had to update babel config too
- Moved Husky hooks
=> BAU - update packages

package-lock.json, package.json, src/browsered/field-validation/field-validation.js, src/browsered/field-validation/field-validation.test.js, src/data/countries.json, src/data/country-record-extension.json, src/index.js, src/nunjucks-filters/country-iso-to-name.js, src/nunjucks-filters/country-iso-to-name.test.js, src/nunjucks-filters/datetime.js, src/nunjucks-filters/datetime.test.js, src/nunjucks-filters/index.js, src/nunjucks-filters/remove-indefinite-articles.js, src/nunjucks-filters/remove-indefinite-articles.test.js, src/nunjucks-filters/slugify.js, src/nunjucks-filters/slugify.test.js, src/utils/countries.js, src/utils/countries.test.js, src/utils/currency-formatter.js, src/utils/currency-formatter.test.js, src/utils/field-validation-checks.js, src/utils/is-valid-email.test.js
To get the ball rolling with using Pay JS Commons, putting our nunjucks filters here as they are a little more straight forward and uniform than other things
=> Nunjucks filters

package-lock.json, package.json
+ eslint-plugin-import@2.18.0
+ eslint-plugin-promise@4.2.1
+ jsdom@14.1.0
+ browser-env@3.2.6
+ @babel/cli@7.4.4
+ moment-timezone@0.5.25
+ @babel/core@7.4.5
+ @babel/preset-env@7.4.5
+ karma@4.1.0
+ lint-staged@8.2.1
+ sinon@7.3.2
+ uglify-js@3.6.0
=> BAU - bulk update packages with npm update

sass/custom/cadw-welsh-government.scss
=> zd3745593 Add Cadw Branding

src/index.js, src/logging-keys/index.js
A file of string constants to be used as structured logging keys in an attempt to encourage consistency.
The keys are identical to those introduced for the Java applications in https://github.com/alphagov/pay-java-commons/commit/37ca42954cfa19a0649a9df7e0b3b07695ae5fa9.
=> PP-5542 Initial structured logging keys for Node.js applications

src/logging-keys/index.js
Key is `x_request_id` to be consistent with the JAVA apps and follow gds way styling.
Husky or whatever, changed the "s to 's
=> PP-5735 Add logging key for correlation id

package-lock.json, package.json
Hadn't been commiting after publishing for the last few releases, so npm got a bit confused
=> Release 2.14.1

README.md
Add instruction to merge a PR with the tagged commit created by `npm publish`
=> BAU Improve publish instructions in README

package-lock.json, package.json
Commit automatically created by `npm publish`
=> Increment version to 2.16.0

src/logging/keys.js
Add logging keys that were added for java apps so the same keys can
be used in node apps.
=> PP-5762 Add additional logging keys

src/logging/keys.js
Update keys to match those in https://github.com/alphagov/pay-java-commons/blob/master/logging/src/main/java/uk/gov/pay/logging/LoggingKeys.java
=> PP-5893: Update keys

sass/custom/torbay-south-devon-nhs-foundation-trust.scss
Make logo for torbay and south devon nhs foundation trust aligned right
and larger.
=> ZD-3873417 Modify custom logo position and size

package-lock.json, package.json, sass/custom/guys-and-st-thomas-nhs-foundation-trust-nhs-care.scss, sass/custom/national-museums-ni.scss
- Hide service name for National Museums NI as requested by Service
- Remove border being displayed on image hover for Guys and St Thomas NHS care
- Bump version to 2.32.1
=> ZD#4091866,#4095823 Fix custom branding styling

package.json
- Add a no-op compile script to enable harmonisation across node
projects
=> PP-6845 Add no-op compile scripts

ci/pipeline.yml, karma.conf.js
- Concourse CI for pay-js-commons
=> PP-6854 pay-js-commons Concourse CI

package-lock.json, package.json
Forgot to check in the automatically created commit when incrementing the
version number for https://github.com/alphagov/pay-js-commons/pull/421. This PR
fixes it manually
=> bau: Manually upgrade version

package-lock.json, package.json
- Bump the version of pay-js-commons
=> ZD Request Bump Version

package-lock.json, package.json
=> ZD Bump Package Version

sass/custom/barking-havering-redbridge-nhs-trust.scss
- Update margin in line with a ZD request to match https://github.com/alphagov/pay-js-commons/blob/master/sass/custom/nhsbsa.scss
=> ZD Update Margin

.secrets.baseline
- Add the `.secrets.baseline` file to the repository
=> BAU Add .secrets.baseline

sass/custom/barking-havering-redbridge-nhs-trust.scss
=> ZD Fix Scss

package-lock.json, package.json
- Now includes all the cookie banner code.
=> PP-6294 - Update NPM package version to 3.0.0

package.json
- update npm package version to 3.0.2
=> PP-6284 update npm package version to 3.0.2

package.json, src/analytics/cookies/validate.js
- fix the if statement when selecting the domain name for prod.
- bump version
=> PP-6284 fix domain name selector and bump version

src/constants/index.js, src/index.js
- Add constants for metadata column constants
=> PP-7360 Add Medata Column constants

sass/custom/nibsc-standards.scss
=> ZD_4487202 Custom branding for NIBSC and MHRA

package-lock.json, package.json, sass/custom/mhra.scss, sass/custom/nibsc-standards.scss
- Hide service name as requested by service
- Bumps version to 3.0.10
=> ZD4487202 Update NBISC & MHRA custom branding

.github/workflows/run-tests.yml, jest.config.js, karma.conf.js, package-lock.json, package.json, src/analytics/cookies/validate.js, src/analytics/cookies/validate.test.js, src/browsered/field-validation/field-validation.js, src/constants/index.js
- Added workflow to run unit tests on Github actions
- Linter fixes
=> PP-8083 Add Github Action to run tests

package-lock.json, package.json
NPM Package version bump to update the `pay-js-commons` package on pay-frontend and pay-products-ui.
=> [ZD-4775772] Bump NPM version for Portsmouth CC

package-lock.json, package.json
I ran `npm compile` as necessary, but in my infinite wisdom, forgot to commit them to the previous PR. This bumps the package version in the Repo.
=> [ZD-4775772] Bump NPM package versions again

src/constants/index.js
Add entries for
* Payment started
* Payment succeeded
* Payment refunded
Reflects backend changes proposed https://github.com/alphagov/pay-webhooks/pull/55
=> PP-9077 Support all initially proposed payment event types

package-lock.json, package.json
- add jest-environment-jsdom to pajage. it no longer ships with jest by default
=> BAU fix Jest Environment

package-lock.json, package.json
Published at https://www.npmjs.com/package/@govuk-pay/pay-js-commons/v/3.4.0
=> PP-9393: Publish pay-js-commons v3.4.0

src/constants/index.js
Bring commons text for webhook subscriptions up to date with the latest docs.
=> PP-9274 Include human readable values for new webhook subscriptions

package-lock.json, package.json, sass/custom/british-pharmacopoeia.scss
Hide service name from the banner
=> ZD-5142738 hide service name from banner

.github/workflows/run-tests.yml
Located and replaced all usages of set-output commands in our workflows.
=> PP-10675: replaced usage of set-output in run-tests.yml

package-lock.json, package.json
- update jsdom version to latest that contains a potential fix
=> BAU update jsdom 

package-lock.json, package.json
=> BAU bump version to 3.8.12

package-lock.json, package.json
- it seems that jsdom 21.x.x break tech-docs. try to revert and see if it fixes the issue
=> BAU revert jsdom update

package-lock.json
Reverts alphagov/pay-js-commons#1150
=> Revert "Bump @babel/cli from 7.21.0 to 7.21.5"

package-lock.json
Reverts alphagov/pay-js-commons#1148
=> Revert "Bump @babel/preset-env from 7.21.4 to 7.21.5"

package-lock.json
Reverts alphagov/pay-js-commons#1151
=> Revert "Bump @babel/core from 7.21.4 to 7.21.5"

package-lock.json
Reverts alphagov/pay-js-commons#1149
=> Revert "Bump xo from 0.54.1 to 0.54.2"

package-lock.json
Reverts alphagov/pay-js-commons#1144
=> Revert "Bump js-cookie from 3.0.1 to 3.0.5"

package-lock.json, package.json
=> BAU bump to version 3.8.16

package-lock.json, package.json
=> BAU bump to version 3.8.17

ci/pipeline.yml
To bring in line with our [other resources in pay-ci](https://github.com/alphagov/pay-ci/blob/master/ci/pipelines/pr.yml#L420).
=> BAU: Disable forks on PR request resource

package-lock.json, package.json
Contains custom branding for Oswestry Town Council.
=> ZD-5424472 Release version 3.11.2

.github/workflows/publish-package.yml
=> BAU fix bad workflow branch trigger

sass/custom/penzance-council.scss
- change the banner colour for Penzance Council
=> ZD-5569361 change banner colour

src/utils/axios-base-client/axios-base-client.test.js
Update axios-base-client test.
- Make sure tests don't proceed if exception meant to be thrown.
=> PP-11683 Extend axios-base-client unit tests.
