- src/nunjucks-filters/slugify.js
- src/nunjucks-filters/slugify.test.js
Extend slugify to convert diacritics used in Welsh which are not
included by default
Co-Authored-By Yancoba Thompson <yancoba.thompson@digital.cabinet-office.gov.uk>
> PP-5012 Slugify Welsh diactritics

- src/logging/format.js
Add an 'environment' field to the logs, so that it is possible to filter
by environment using a Splunk text search. Splunk does currently extract
the environment from the source if it is explicitly searched on using
e.g. the term 'environment="production-2"', but some of our reports use
a text search so will not pick up on all log lines.
The text search continues to work for many logs where the environment is
included in some way in the log message, but not for others where it
isn't so it makes sense to get rid of this ambiguity.
In the apps producing the logs, we get the environment from an
environment variable which is already configured for use by Sentry.
> PP-5764 Add environment field to logs

- src/logging/request-log-format.js
Add a field in the format we provide to morgan for logging to log the
correlation id. Modify the class so that it takes a parameter providing
it with the name of the correlation id header for the app.
> PP-5762 Log correlation id for incoming requests

- src/logging/index.js
How we do the export in `request-log-format.js` changed, but the require in `logging/index.js` wasn't updated. This fixes this.
> PP-5762 Fix export for request log format

- package-lock.json
- package.json
- Bumps `pay-js-commons` version to 2.20.0 ( currently published in npm )
> BAU - Bump version to 2.20.0

- package-lock.json
- package.json
2.23.0 was released previously but the commit to bump the version wasn't pushed. 2.22.1 was subsequently released. Make a new 2.24.0 release to fix the versioning.
> Tag 2.24.0

- package.json
We shouldn't run test files through our build steps -- don't do that.
> BAU Ignore test files from browserify script

- package-lock.json
- package.json
- sass/custom/guys-and-st-thomas-nhs-foundation-trust-nhs-care.scss
- Update custom branding styling for `Guy's & St Thomas' customer card payments` service as requested by service ( Zendesk #4095823)
- Bump version to 2.32.2
-----
> ZD#4095823 Update custom branding styling

- package-lock.json
- package.json
- src/browsered/field-validation/field-validation.test.js
- src/utils/is-valid-email.test.js
* major upgrade to mocha (updated from ~2 years ago) 
* the way the project manages imports has changed and this messes with browserify trying to transpile the tests, specify mocha as the testing environment and remove local imports
* fix lint issues with anything staged\
* all tests pass
* `npm audit` returns 0 vulnerabilities
* CI is green
> BAU npm audit vulnerabilities

- ci/pipeline.yml
Allows changes to pipeline to be auto deployed on merge. Users do not need to set the pipeline changes themselves.
> BAU: Allow self-updating Concourse pipelines

- sass/custom/adur-and-worthing-council.scss
> zd4195581: Right align Adur&Worthing borough logo

- jest.config.js
- karma.conf.js
- package-lock.json
- package.json
- src/analytics/cookies/banner.html
- src/analytics/cookies/validate.js
- src/analytics/cookies/validate.test.js
- src/analytics/index.js
* Use existing browerify dev dependency to build cookie consent code
* Bundle a shared banner template
* Provide an interface to let upstream code enable tracking IFF the
consent cookies are present
* Add consent and reject cookie interface logic
* Exposes two helper methods to manage analytics consent cookies
* build a consent banner if the consent cookie hasn't been set
* give upstream code the ability to check if consent has been provided
by the user
* Provide a hook for upstream code to perform an action when the user
pressed 'Yes' on the analytics consent banner.
* Ensure backwards compatability by babelifying analytics code
distribution. Remove `path` library as there is no need for this to be
bundled for its one use case.
* Adds `js-cookie` library to intreface with browser cookies …
> PP-6284 include common analytics cookies

- src/analytics/cookies/banner.html
- src/analytics/cookies/validate.js
- src/analytics/cookies/validate.test.js
* Update banner.html with css styling
* functionality and tests for Cookie banner > confirmation message
* Add test to check that the confirmation message is shown when you you click Yes or No
on the cookie banner.
* Also test that the hide link in the confirmation message hides the banner.
> PP-6284 enable analytics with consent banner

- src/analytics/cookies/validate.js
- Fix issue with cookie domain being set incorrectly.
- We only set the cookie domain to `payments.service.gov.uk` for PROD.
- For all other domains, we do not set the cookie domain.
- For localhost, we do not set the cookie domain.
> PP-6284 Cookie Banner - fix cookie domain

- package-lock.json
- package.json
- sass/custom/mhra.scss
- Fixes styling for service name
- Bump version to 3.0.9
Previously logo looks like
and now
> ZD4487202 Fix styling for MHRA custom branding

- src/analytics/cookies/banner.html
- This will make it easier for screen readers to navigate through the cookie banner.
> PP-8015 Cookie banner - replace "aria-describedby" with "aria-label=cookie banner"

- src/nunjucks-filters/datetime.js
- src/nunjucks-filters/datetime.test.js
Add filter that formats dates in the GOV.UK recommended style, e.g. "7 July 2021"
> PP-8219 Add Nunjucks filter to format long date

- package-lock.json
- package.json
- sass/custom/lewisham-and-greenwich-nhs-trust.scss
This is an amendment to the Lewisham & Greenwich NHS Trust custom branding CSS to swap around the Logo and Service Title elements - the Logo asset in question is designed to be right-aligned and the Sass changes included should rectify this.
The `float:right;` should be applied to all display sizes as this will also put it in the right place on mobile.
https://github.com/alphagov/pay-js-commons/pull/776
> ZD-4769105: Change alignment of L&G NHS Logo

- sass/custom/portsmouth.scss
It has been requested if there could be approximately 20px worth of padding surrounding the Portsmouth CC logo, in order to more closely conform to PCC's branding guidelines.
> [ZD-4775772] Adding requested padding to PCC Logo

- src/nunjucks-filters/slugify.js
- src/nunjucks-filters/slugify.test.js
A service was running into issues as their service name contains commas,
causing the payment link that was created to have a strange looking URL
that was then blocked by NAXSI rules.
Strip all special characters from generated URLs.
Removing the characters runs after slugify has run, so some special
characters will be replaced by words, such as $ -> dollar
> BAU Strip all special characters for generating URLs

- .github/workflows/run-tests.yml
- .pre-commit-config.yaml
- .secrets.baseline
**WHAT**
•	added a new github action to run detect-secrets
•	updated the pre-commit config to update the detect-secrets hook to version 1.4
•	rebaselined the repository's secrets baseline
Based on [alphagov/pay-webhooks#510](https://github.com/alphagov/pay-webhooks/pull/510)
**For reviewers**
•	ensure your local version of detect-secrets matches the latest version in use on this branch
•	run detect-secrets scan and ensure output matches the latest .secrets.baseline, the only change should be the generated timestamp
> PP-10116: Add detect-secrets workflow and update version

- package-lock.json
- package.json
- sass/custom/nibsc-standards-2023-01.scss
Adds a width to ensure the SVG is displayed.
Version 3.8.5 has been published to NPM.
> ZD-5142738: Add new NIBSC sass for displaying SVG logo

- package-lock.json
- package.json
Reverts alphagov/pay-js-commons#1093
(the post-merge tests failed, possibly because of Dependabot not rebasing properly)
> Revert "Bump jsdom from 20.0.3 to 21.1.0"

- package-lock.json
- package.json
- Bumps version to 3.11.1 post branding changes https://github.com/alphagov/pay-js-commons/pull/1207
- Had to do a patch release as the minor version release did not include intended changes.
> Bump version to 3.11.1

- karma.conf.js
- src/browsered/field-validation/field-validation.test.js
- amend karma configuration to:
- prevent excluding certain tests erroneously
- fix bug where `GOVUKPAY` was not being assigned to the global `window` object during headless test runs
> BAU update karma configuration

- src/browsered/field-validation/field-validation.test.js
- src/utils/field-validation-checks.js
Given we've allowed apostrophe's ([NAXSI rule 1013](https://github.com/nbs-system/naxsi/blob/master/naxsi_config/naxsi_core.rules#L37)) on [creating payment links](https://github.com/alphagov/pay-infra/blob/master/provisioning/terraform/modules/pay_microservices_v2/products-ui/files/products-ui.naxsi) we should relax the rule here in pay-js-commons.
> ZD-5469011: Allow apostrophe's in prefilled payment link references

- karma.conf.js
- package-lock.json
- package.json
- src/utils/axios-base-client/axios-base-client.js
- src/utils/axios-base-client/axios-base-client.test.js
- src/utils/axios-base-client/errors.js
- src/utils/axios-base-client/errors.test.js
- Add Axios and other related dependencies.
- Add new version of base client script using ‘axios’ instead of ‘request’ library.
- Add accompanying unit test using the Jest framework.
- In `pay-js-commons` - we are gradually moving away from the existing
Karma tests. Everything will be moved to Jest.
- Update Karma tests configuration
- Make it clearer which files are excluded from Karma testing by using
the `exclude` attribute.
- Fix issue with Axios - use the globals=true attribute.
> Pp 11683 add axios base client and karma test updates

- src/utils/axios-base-client/axios-base-client.test.js
PP-11683 Replace `request` library with `axios`
https://payments-platform.atlassian.net/browse/PP-11683
Summary of changes
Include specific tests for 'PUT', 'PATCH' and 'DELETE' methods.
> PP-11683 Extend axios-base-client unit tests.

- README.md
- package-lock.json
- package.json
- Contains a breaking change - the HTTPS base client is now exported in a simpler way.
- Therefore bumping major version to stop apps from auto updating to this version.
> PP-12468 Bumping major version for HTTPS base client

- README.md
- The axios base client is used by consuming apps to call API endpoints.
- The readme has been updated to include information about the Axios base client.
> PP-11682 - Update readme to include info about the Axios base client

- .github/workflows/prevent-merge-if-release-open.yml
- .github/workflows/publish-package.yml
- .github/workflows/run-tests.yml
Upgrades the following to run on Node 20:
`actions/checkout`
`actions/setup-node`
`actions/github-script`
> PP-12244: Upgrade deprecated Github Actions

- README.md
Adds missing sections to repo README.
Text based on the [pay-frontend README](https://github.com/alphagov/pay-frontend?tab=readme-ov-file#licence).
> BAU: Add missing Licence and Vulnerability Disclosure to README

- src/utils/countries.js
- src/utils/countries.test.js
- Update the function to handle null and invalid country codes gracefully.
- Re-organise the file to group similar tests together.
> PP-14242 Update the countries > translateAlpha2 function

- package.json
- src/utils/axios-base-client/errors.js
- src/utils/axios-base-client/errors.test.js
The axios-base-client errors tests have previously been excluded when the unit tests are run. The only error class still in use is the `RESTClientError`. This remains, while all the others have been removed along with the corresponding tests. 
The test has been re-enabled by running everything within the `src/utils/axios-base-client` directory.
> PP-13427 Clean up errors.test.js

- karma.conf.js
- package.json
- src/nunjucks-filters/country-iso-to-name.test.js
- src/nunjucks-filters/datetime.test.js
- src/nunjucks-filters/remove-indefinite-articles.test.js
- src/nunjucks-filters/slugify.test.js
- src/utils/countries.test.js
- src/utils/currency-formatter.test.js
- src/utils/is-valid-email.test.js
- This repo uses Karma (existing tests) and Jest (used for newer tests).
- This PR updates some existing tests to use Jest.
- Updated the Karam config to ignore these files when it is running as Jest will test them instead.
- Updated the NPM Jest command to run the updated tests.
- Future PRs will migrate the remaining tests.
> PP-14403 Migrate unit tests to use Jest

- package.json
- Need to manually bump version so it triggers a new automated PR to bump the version -> so we can merge that PR and automatically publish the NPM module.
- The previous automated PR was closed because it used NPM auth tokens and we have updated GHA to use OIDC.
> PP-14551 Manually bump version

- .github/workflows/publish-package.yml
- package-lock.json
- package.json
- Node 22 - which is the one currently being used, comes with NPM 10.x
- To use OIDC we need NPM 11.x.
- For now, added step to upgrade NPM to 11.6.0 as part of the GHA publish workflow.
- In the future, we will upgradef the version of Node which will come bundled with NPM 11.x.
> PP-14551 GHA - Upgrade NPM when publishing to NPM
